export const english_summary = 'The video titled "Introduction to Programming" is a 90-minute series consisting of 21 segments, hosted by Steven and Sean. It aims to cover the basics of computer programming applicable to any programming language. The video starts with the fundamental question of what programming is and gradually progresses to discuss common features of computer science such as loops and arrays. It also provides strategies for planning, reading, and debugging code. The video avoids language-specific topics like object-oriented coding and command line navigation. It concludes by encouraging viewers to explore further possibilities in coding, like contributing to GitHub projects or collaborating on personal projects. The video is part of a miniseries on the channel "Low Point or Exception".'

export const  hindi_summary = "'प्रोग्रामिंग का परिचय' शीर्षक वाला वीडियो 90 मिनट की श्रृंखला है जिसमें 21 खंड शामिल हैं, जिसे स्टीवन और सीन द्वारा होस्ट किया गया है। इसका उद्देश्य किसी भी प्रोग्रामिंग भाषा पर लागू कंप्यूटर प्रोग्रामिंग की मूल बातें शामिल करना है। वीडियो मूल प्रश्न से शुरू होता है कि प्रोग्रामिंग क्या है और धीरे-धीरे कंप्यूटर विज्ञान की सामान्य विशेषताओं जैसे लूप और एरे पर चर्चा करने के लिए आगे बढ़ती है। यह कोड की योजना बनाने, पढ़ने और डिबगिंग के लिए रणनीतियाँ भी प्रदान करता है। वीडियो में ऑब्जेक्ट-ओरिएंटेड कोडिंग और कमांड लाइन नेविगेशन जैसे भाषा-विशिष्ट विषयों से परहेज किया गया है। यह दर्शकों को कोडिंग में आगे की संभावनाएं तलाशने के लिए प्रोत्साहित करने के साथ समाप्त होता है, जैसे GitHub परियोजनाओं में योगदान करना या व्यक्तिगत परियोजनाओं पर सहयोग करना। वीडियो 'लो पॉइंट या एक्सेप्शन' चैनल पर एक लघु श्रृंखला का हिस्सा है।"

export const spanish_summary = `El vídeo titulado "Introducción a la programación" es una serie de 90 minutos que consta de 21 segmentos, presentada por Steven y Sean. Su objetivo es cubrir los conceptos básicos de programación informática aplicables a cualquier lenguaje de programación. El vídeo comienza con la pregunta fundamental de qué es la programación y avanza gradualmente para analizar características comunes de la informática, como bucles y matrices. También proporciona estrategias para planificar, leer y depurar código. El video evita temas específicos del idioma, como la codificación orientada a objetos y la navegación por línea de comandos. Concluye animando a los espectadores a explorar más posibilidades en la codificación, como contribuir a proyectos de GitHub o colaborar en proyectos personales. El video es parte de una miniserie del canal "Punto Bajo o Excepción".`

export const french_summary = `La vidéo intitulée "Introduction à la programmation" est une série de 90 minutes composée de 21 segments, animée par Steven et Sean. Il vise à couvrir les bases de la programmation informatique applicables à tout langage de programmation. La vidéo commence par la question fondamentale de ce qu'est la programmation et progresse progressivement pour discuter des caractéristiques communes de l'informatique telles que les boucles et les tableaux. Il fournit également des stratégies de planification, de lecture et de débogage du code. La vidéo évite les sujets spécifiques au langage comme le codage orienté objet et la navigation en ligne de commande. Il se termine en encourageant les téléspectateurs à explorer d'autres possibilités en matière de codage, comme contribuer à des projets GitHub ou collaborer sur des projets personnels. La vidéo fait partie d'une mini-série sur la chaîne "Point Bas ou Exception".`

export const portuguese_summary = `O vídeo intitulado "Introdução à Programação" é uma série de 90 minutos composta por 21 segmentos, apresentada por Steven e Sean. Tem como objetivo cobrir os fundamentos da programação de computadores aplicáveis ​​a qualquer linguagem de programação. O vídeo começa com a questão fundamental do que é programação e progride gradualmente para discutir recursos comuns da ciência da computação, como loops e arrays. Ele também fornece estratégias para planejamento, leitura e depuração de código. O vídeo evita tópicos específicos da linguagem, como codificação orientada a objetos e navegação por linha de comando. Conclui incentivando os espectadores a explorar outras possibilidades de codificação, como contribuir para projetos do GitHub ou colaborar em projetos pessoais. O vídeo faz parte de uma minissérie do canal “Ponto Baixo ou Exceção”.`

