# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - charity

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://eduguidechatbotdockerreg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f021c5cc85e84ca486b6a290b05d9e5b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_db36a714a8d14ac9914ba7255288979b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: eduguidechatbotdockerreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f021c5cc85e84ca486b6a290b05d9e5b }}/charity:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'charity'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_39ac8389ae354f77a4043efd3817d2b0 }}
        images: 'eduguidechatbotdockerreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f021c5cc85e84ca486b6a290b05d9e5b }}/charity:${{ github.sha }}'